config/routes.rb
Rails.application.routes.draw do
  resources :userrs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
end

app/models/userr.rb
class Userr < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/userrs_controller.rb
class UserrsController < ApplicationController
  before_action :set_userr, only: %i[ show edit update destroy ]

  # GET /userrs or /userrs.json
  def index
    @userrs = Userr.all
  end

  # GET /userrs/1 or /userrs/1.json
  def show
  end

  # GET /userrs/new
  def new
    @userr = Userr.new
  end

  # GET /userrs/1/edit
  def edit
  end

  # POST /userrs or /userrs.json
  def create
    @userr = Userr.new(userr_params)

    respond_to do |format|
      if @userr.save
        format.html { redirect_to userr_url(@userr), notice: "Userr was successfully created." }
        format.json { render :show, status: :created, location: @userr }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @userr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userrs/1 or /userrs/1.json
  def update
    respond_to do |format|
      if @userr.update(userr_params)
        format.html { redirect_to userr_url(@userr), notice: "Userr was successfully updated." }
        format.json { render :show, status: :ok, location: @userr }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @userr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userrs/1 or /userrs/1.json
  def destroy
    @userr.destroy

    respond_to do |format|
      format.html { redirect_to userrs_url, notice: "Userr was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userr
      @userr = Userr.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def userr_params
      params.require(:userr).permit(:name, :age, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/userrs_helper.rb
module UserrsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProyectoPower</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/userrs/_form.html.erb
<%= form_with(model: userr) do |form| %>
  <% if userr.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(userr.errors.count, "error") %> prohibited this userr from being saved:</h2>

      <ul>
        <% userr.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/userrs/_userr.html.erb
<div id="<%= dom_id userr %>">
  <p>
    <strong>Name:</strong>
    <%= userr.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= userr.age %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= userr.email %>
  </p>

</div>

app/views/userrs/edit.html.erb
<h1>Editing userr</h1>

<%= render "form", userr: @userr %>

<br>

<div>
  <%= link_to "Show this userr", @userr %> |
  <%= link_to "Back to userrs", userrs_path %>
</div>

app/views/userrs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Userrs</h1>

<div id="userrs">
  <% @userrs.each do |userr| %>
    <%= render userr %>
    <p>
      <%= link_to "Show this userr", userr %>
    </p>
  <% end %>
</div>

<%= link_to "New userr", new_userr_path %>

app/views/userrs/new.html.erb
<h1>New userr</h1>

<%= render "form", userr: @userr %>

<br>

<div>
  <%= link_to "Back to userrs", userrs_path %>
</div>

app/views/userrs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @userr %>

<div>
  <%= link_to "Edit this userr", edit_userr_path(@userr) %> |
  <%= link_to "Back to userrs", userrs_path %>

  <%= button_to "Destroy this userr", @userr, method: :delete %>
</div>